### ISSUE TITLE
JSONパーサーライブラリが複数ある問題

### ISSUE THREAD

**Issue by chigichan24** [cyder/SyncPod-Android#131]
JacksonとGsonの2つが共存していて，パーサーライブラリが複数ある問題．

動作としては問題はないが，どちらかにすべき．

なにか2つを使わないといけない理由があるなら知りたい．

**Comment by Mori-Atsushi** [comment]
まじ？Gsonしか使ってるイメージなかった。
どこかのコピペで混じったか…

**Comment by chigichan24** [comment]
コピペで混ぜるな(ぷちキレ
